### ISSUE TITLE
double flux update CAN happen in upbnd

### ISSUE THREAD

**Issue by rjleveque** [clawpack/geoclaw#247] opened 2017-02-26 17:22 UTC
@mjberger: @donnaaboise is running a GeoClaw problem where this gets printed every time step for a while:

```
 ***  double flux update CAN happen in upbnd ***
```

Is this something to worry about or just a left over debugging statement?

**Comment by mjberger** [comment] 2017-02-26 20:32
that is not good. Save the setup please.

**Comment by donnaaboise** [comment] 2017-02-27 17:24
What exactly should I save?  I have all of the data files, and can reproduce it on 8 cores on our cluster (but unfortunately not yet on my laptop).

**Comment by mandli** [comment] 2018-01-03 23:06
This thread has gone quite but I am a bit concerned as we have been able to consistently produce this error but only with the intel compiler.  It seems to be pretty robust in terms of what compilation flags are used.  I can go through the debugger and see what might be wrong but is there somewhere we should look explicitly for this (I sadly do not have access to total view).

**Comment by mjberger** [comment] 2018-01-05 19:40
Do you think it's a compiler error? I thought I could reproduce it only with some compilers flags but don't remember which.  When I am back at my desktop (i.e. with totalview) we should try to get to the bottom of it.  

 — Marsha

**Comment by mandli** [comment] 2018-01-05 19:45
It very well could be.  There may be some combination of flags that do not trigger the error but it would be nice to know what those are at the very least and the source of the problem.

**Comment by mandli** [comment] 2018-01-12 02:25
#283 is meant to help debug this problem if people who can recreate the problem can try that out.  It basically prints out some debugging info to `fort.amr` we can hopefully look at.

**Comment by mandli** [comment] 2019-08-16 16:29
Fixed in clawpack/amrclaw#207.  Note that this seems to be a compiler specific issue and more than likely a bug.

**Closed by mandli** 2019-08-16 16:29 UTC
